git:
  depth: 100

language: generic

os:
  - linux

sudo: false

env:
  global:
    - PYENV_VERSION=3.6
    - CHANS_DEV="-c pyviz/label/dev"
    - CHANS_REL="-c pyviz"
    - PKG_TEST_PYTHON="--test-python=py27 --test-python=py36"
    - PYPI="https://upload.pypi.org/legacy/"

cache:
  directories:
    - $HOME/miniconda

before_cache:
  - rm -rf $HOME/miniconda/pkgs
  - rm -rf $HOME/miniconda/conda-bld/*
  - rm -rf $HOME/miniconda/envs/*/conda-bld  

# quick hack to determine what tag is (improvements welcomed)
#     release: ^v(\d+|\.)*[^a-z]\d*$
# dev release: ^v(\d+|\.)*[a-z]\d*$

stages:
  - test
  - name: conda_dev_package
    if: branch = switch_to_pyctdev
#    if: tag =~ ^v(\d+|\.)*[a-z]\d*$
  - name: pip_dev_package
    if: tag =~ ^v(\d+|\.)*[a-z]\d*$
#    if: branch = switch_to_pyctdev
  - name: conda_package
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$
  - name: pip_package
    if: tag =~ ^v(\d+|\.)*[^a-z]\d*$
  - name: docs
    if: tag =~ ^v(\d+|\.).*$


jobs:
  include:

    ########## DEVELOPER INSTALL ##########

    - &conda_default
      stage: test
      env: DESC="dev test_all"
      before_install:
        # install doit/pyctdev and use to install miniconda...
        - pip install pyctdev && doit miniconda_install && pip uninstall -y doit pyctdev
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        # ...and now install doit/pyctdev into miniconda
        - conda install -c pyviz/label/dev pyctdev && doit ecosystem_setup
      install:
        - doit env_create $CHANS_DEV --python=$PYENV_VERSION
        - source activate test-environment
        - doit develop_install -o examples -o tests $CHANS_DEV
        - doit env_capture
      script: doit test_all

    # python 2 flake checking typically catches python 2 syntax
    # errors where python 3's been assumed...
    - <<: *conda_default
      env: DESC="py2 flakes" PYENV_VERSION=2.7
      script: doit test_lint

    ########## END-USER PACKAGES ##########

    ## dev packages

    - &pip_default
      env: PYPI="https://test.pypi.org/legacy/" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      stage: pip_dev_package
      before_install: pip install pyctdev && doit ecosystem=pip ecosystem_setup
      install:
        - unset PYENV_VERSION && pyenv global 3.6 2.7
        - doit ecosystem=pip package_build $PKG_TEST_PYTHON --test-group=unit
        - doit ecosystem=pip package_build $PKG_TEST_PYTHON --test-group=all
      script: doit ecosystem=pip package_upload -u $TPPU -p $TPPP -r ${PYPI}

    - <<: *conda_default
      stage: conda_dev_package
      env: DESC="" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install:
        - doit package_build $CHANS_DEV $PKG_TEST_PYTHON --test-group=unit
        - doit package_test $CHANS_DEV $PKG_TEST_PYTHON --test-group=examples --test-requires=examples
      script: doit package_upload --user=ceball --token=$CONDA_UPLOAD_TOKEN_TMP --label=dev

    ## release packages

    - <<: *pip_default
      env: TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      stage: pip_package
      script: doit ecosystem=pip package_upload -u $PPU -p $PPP -r ${PYPI}

    - <<: *conda_default
      stage: conda_package
      env: DESC="" TRAVIS_NOCACHE=$TRAVIS_JOB_ID
      install: doit package_build $CHANS_REL $PKG_TEST_PYTHON --test-group=all
      script: doit package_upload --token=$CONDA_UPLOAD_TOKEN_AGAIN  --label=dev --label=main


    ########## DOCS ##########

    - <<: *conda_default
      stage: docs
      env: DESC="docs" CHANS_DEV="-c pyviz/label/dev"
      script:
        - doit develop_install $CHANS_DEV -o doc
        - doit docs
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          fqdn: parambokeh.pyviz.org
          local_dir: ./doc/_build/html
          repo: ioam-docs/parambokeh-dev
          on:
            tags: true
            all_branches: true
            condition: $TRAVIS_TAG =~ [0-9]+[a-z][0-9]*$
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: ./doc/_build/html
          on:
            tags: true
            all_branches: true
            condition: $TRAVIS_TAG =~ [0-9]+[^a-z][0-9]*$
